pipeline {
    agent any

    stages {
        stage('Check Docker Availability') {
            steps {
                bat 'where docker'
            }
        }
        stage('Inspect Docker Image') {
            steps {
                bat 'docker inspect -f "{{.Id}}" node:16-alpine'
            }
        }
    }
}
